title: Hoyt Family Recipes
description: >
  Recipes from our Armenian, German, British, Scottish, and American heritage

show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
