title: Hoyt Family Recipes
description: >
  Recipes from our Armenian, German, British, Scottish, and American heritage

show_excerpts: true

# See explanation of baseurl at:
#  https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /recipes

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
